# Generated by Django 5.0.1 on 2024-03-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('dataNascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('serieturma', models.CharField(max_length=50)),
                ('turno', models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno')])),
            ],
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('dataDevolucao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('dataEmprestimo', models.DateField()),
                ('dataPrevistaDevolucao', models.DateField()),
                ('serieturma', models.CharField(max_length=50)),
                ('turno', models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno')])),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('autor', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=200)),
                ('anoEdicao', models.IntegerField()),
                ('sinopse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('dataNascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('disciplina', models.CharField(max_length=50)),
                ('turno', models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno')])),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('serieturma', models.CharField(max_length=50)),
                ('turno', models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno')])),
            ],
        ),
    ]
